name: Validate Commit Messages

on:
  pull_request:
    branches: [ main ]

jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit messages
        run: |
          COMMITS=$(git log --format=%s origin/main..HEAD)
          BRANCH="${{ github.head_ref }}"

          for COMMIT in $COMMITS; do
            if [[ ! "$COMMIT" =~ ^${BRANCH}+:\s.+\s-v[0-9]+\.[0-9]+$ ]]; then
              echo "❌ Invalid commit message: $COMMIT"
              echo "✅ Expected: ${BRANCH} message -vX.Y"
              exit 1
            fi
          done